version: '3.8'

services:
  api:
    build: .
    container_name: oldmonk-api
    restart: unless-stopped
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - ./logs:/usr/src/app/logs

  mongo:
    image: mongo:7
    container_name: oldmonk-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
